//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OQA_System1.ClientsFolder.Web_ADMinFolder
{


    public partial class frmDashBoard1
    {
    }
}
